config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'

  get 'welcome/about'

  resources :lists, except: [:index] do
    resources :items, only: [:create, :destroy]
  end

   root to: 'welcome#index'

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :list

  def days_left
      (DateTime.now.to_date - created_at.to_date).to_i
   end

end

app/models/list.rb
class List < ActiveRecord::Base
  belongs_to :user
  has_many :items
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
         
  has_one :list
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
 
   protected
 
   def configure_permitted_parameters
     devise_parameter_sanitizer.for(:sign_up) << :name
   end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
   respond_to :html, :js
   before_action :authenticate_user! # users must be signed in before any lists_controller method

  def create 
    @item = Item.new(params.require(:item).permit(:name))
    @item.list = current_user.list
     if @item.save
       flash[:notice] = "You're item was added to the list!"
       redirect_to @item.list
     else
       flash[:error] = "You and your Item suck - try again"
       render @item.list
     end
  end



   def destroy
    @list = current_user.list
    @item = Item.find(params[:id])

    if @item.destroy
      flash[:notice] = "Item was removed."
    else
      flash[:error] = "Item couldn't be deleted. Try again."
       
    end
     respond_with(@item) do |format|
       format.html { redirect_to @list }
     end
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
   before_action :authenticate_user! # users must be signed in before any lists_controller method

  def show
    @list = current_user.list
    if @list 
        @current_items_in_the_list = @list.items
        @item = Item.new
    end
     
  end


  def new   
    @list = List.new 
  end

  def create
    if current_user.list
      flash[:notice] = "You already have one list, bitch!"
       redirect_to current_user.list
      return   false
    end
     @list = List.new(params.require(:list).permit(:title))
     @list.user = current_user
     if @list.save
       flash[:notice] = "Created list!"
       redirect_to @list
     else
       flash[:error] = "You and your list suck - try again"
       render :new
     end
  end

  def edit
    @list = current_user.list
  end

  def update
     @list = current_user.list
     if @list.update_attributes(params.require(:list).permit(:title))
       flash[:notice] = "List title was updated."
       redirect_to @list
     else
       flash[:error] = "You and your list suck - try again"
       render :edit
     end
   end

  def destroy
     @list = List.first

     if @list.destroy
       flash[:notice] = "The list was succesfully deleted"
       redirect_to list_path
     else
       flash[:error] = "There was an error deleting the topic."
       render list_path
     end
   end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/_form.html.erb
    <%= form_for [@list,@item] do |f| %>
        <%= f.label :name %>
        <%= f.text_field :name %>
        <%= f.submit "Add",class: "btn btn-success" %>
    <% end %>

app/views/items/_item.html.erb
<% if item %>
    <li <%= "id=item_#{item.id}" %> >
      <%= item.name %><br/>
     
      <%= link_to "", [@list,item] , method: :delete, class: 'glyphicon glyphicon-ok',remote: true %>
    </li>
<% end %>    

app/views/items/destroy.js.erb
<% if @item.destroyed? %>
   $('#item_' +<%= @item.id %>).hide();
 <% else %>
   $('#item_' +<%= @item.id %>).prepend("<div class='alert alert-danger'><%= flash[:error] %></div>");
 <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocitoff</title>
     <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
<ul class="nav nav-tabs">
  <li><%= link_to "Home", welcome_index_path %></li>
  <% if !user_signed_in? %>
        <li><%= link_to "Sign in", new_user_session_path %></li>
        <li><%= link_to "Register", new_user_registration_path %></li>
  <% end %>
  <li><%= link_to "About", welcome_about_path %></li>
  <li>
    <% if user_signed_in? %>
        <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
    <% end %>

  </li>
</ul>
  <% if notice %>
       <p class="alert alert-warning"><%= notice %></p>
  <% end %>
  <% if alert %>     
       <p class="alert alert-danger"><%= alert %></p>
  <% end %>     
<%= yield %>
</div>

</body>
</html>

app/views/lists/edit.html.erb
 <%= form_for @list do |f| %>
   <%= f.label :title %>
   <%= f.text_field :title %>
   <%= f.submit "Save" %>
 <% end %>

app/views/lists/new.html.erb
 <%= form_for @list do |f| %>
   <%= f.label :title %>
   <%= f.text_field :title %>
   <%= f.submit "Save" %>
 <% end %>

app/views/lists/show.html.erb
 <h1>Your list:</h1>
 <% if @list.nil? %>
  <h2>You suck you don't have any lists</h2>
   <%= link_to "New To-do List", new_list_path, class: 'btn btn-success' %>
 <% else %>
    <h2><%= @list.title %> </h2>
    
      <%= link_to "Delete", list_path, class: 'btn btn-danger', method: :delete  %><%= link_to "Edit", edit_list_path, class: 'btn btn-info'  %>
    <h3>Add to-do item</h3>
        <%= render :partial => "items/form" %>
    <ol>
      <%= render :partial => "items/item", :collection => @current_items_in_the_list, :as => :item %>
    </ol>

 <% end %>

app/views/welcome/about.html.erb
<h1>About page</h1>
<p>You shouldn't expect much of this page</p>
<small>Lev Andelman</small>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <h1>Welcome to Blocitoff</h1>
  <p>The most amazing to-do list in the world</p>
  <p><a class="btn btn-primary btn-lg" href="#" role="button">Tutorial for dumbasses</a></p>
</div>